### ISSUE TITLE
Errors running make

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/sphinxcontrib-jupyter.minimal#2]
Here were my steps:
1. Windows10, Installed Anaconda3
1. Did a  `conda update --prefix C:\bin\Anaconda3 anaconda` just to be sure I have the latest copy
1. Cloned https://github.com/QuantEcon/sphinxcontrib-jupyter
   - Ran `python setup.py install` in the cloned directory.  Seemed to install correctly, and didn't mention any missed dependencies.
   - I did this because https://github.com/QuantEcon/sphinxcontrib-jupyter.minimal#simple_notebookrst says I need to use `master`.
1. Cloned  https://github.com/QuantEcon/sphinxcontrib-jupyter.minimal
1. In the directory, went `./make jupyter`, following instructions
The output is
```
PS C:\Users\jlperla\Documents\libraries\sphinxcontrib-jupyter.minimal> ./make jupyter
Running Sphinx v1.7.4
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [jupyter]: targets for 2 source files that are out of date
updating environment: 2 added, 0 changed, 0 removed
reading sources... [100%] simple_notebook
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [ 50%] index
Exception occurred:
  File "c:\bin\anaconda3\lib\site-packages\sphinxcontrib\jupyter\writers\utils.py", line 113, in get_source_file_name
    raise ValueError("File path does not exist in the source directory")
ValueError: File path does not exist in the source directory
The full traceback has been saved in C:\Users\jlperla\AppData\Local\Temp\sphinx-err-nu1ccslz.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
The contents of that log file mentioned is
```
# Sphinx version: 1.7.4
# Python version: 3.6.5 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:
#   checking consistency...
#   
#   done
#   
#   preparing documents...
#   
#   done
#   
#   writing output... [ 50%] index
#   
# Loaded extensions:
#   alabaster (0.7.10) from C:\bin\Anaconda3\lib\site-packages\alabaster\__init__.py
#   sphinxcontrib.jupyter (0.2.1) from c:\bin\anaconda3\lib\site-packages\sphinxcontrib\jupyter\__init__.py
#   sphinx.ext.mathjax (1.7.4) from C:\bin\Anaconda3\lib\site-packages\sphinx\ext\mathjax.py
Traceback (most recent call last):
  File "C:\bin\Anaconda3\lib\site-packages\sphinx\cmdline.py", line 304, in main
    app.build(args.force_all, filenames)
  File "C:\bin\Anaconda3\lib\site-packages\sphinx\application.py", line 331, in build
    self.builder.build_update()
  File "C:\bin\Anaconda3\lib\site-packages\sphinx\builders\__init__.py", line 338, in build_update
    'out of date' % len(to_build))
  File "C:\bin\Anaconda3\lib\site-packages\sphinx\builders\__init__.py", line 399, in build
    self.write(docnames, list(updated_docnames), method)
  File "C:\bin\Anaconda3\lib\site-packages\sphinx\builders\__init__.py", line 436, in write
    self._write_serial(sorted(docnames))
  File "C:\bin\Anaconda3\lib\site-packages\sphinx\builders\__init__.py", line 445, in _write_serial
    self.write_doc(docname, doctree)
  File "c:\bin\anaconda3\lib\site-packages\sphinxcontrib\jupyter\builders\jupyter.py", line 71, in write_doc
    self.writer.write(doctree, destination)
  File "C:\bin\Anaconda3\lib\site-packages\docutils\writers\__init__.py", line 80, in write
    self.translate()
  File "c:\bin\anaconda3\lib\site-packages\sphinxcontrib\jupyter\writers\jupyter.py", line 21, in translate
    visitor = self.translator_class(self.builder, self.document)
  File "c:\bin\anaconda3\lib\site-packages\sphinxcontrib\jupyter\writers\translate_all.py", line 12, in __init__
    super().__init__(builder, document)
  File "c:\bin\anaconda3\lib\site-packages\sphinxcontrib\jupyter\writers\translate_code.py", line 30, in __init__
    self.settings.env.srcdir)
  File "c:\bin\anaconda3\lib\site-packages\sphinxcontrib\jupyter\writers\utils.py", line 113, in get_source_file_name
    raise ValueError("File path does not exist in the source directory")
ValueError: File path does not exist in the source directory

**Comment by arnavs** [comment]
@jlperla Had asked me to look into this error. Here's what I found: 

1. The line that throws an error is this one: https://github.com/QuantEcon/sphinxcontrib-jupyter/blob/master/sphinxcontrib/jupyter/writers/utils.py#L113.
2. If we change the UNIX-style `/` to the Windows-style `\\` in lines [108](https://github.com/QuantEcon/sphinxcontrib-jupyter/blob/master/sphinxcontrib/jupyter/writers/utils.py#L108) and [109](https://github.com/QuantEcon/sphinxcontrib-jupyter/blob/master/sphinxcontrib/jupyter/writers/utils.py#L109), this issue goes away. 

cc: @NickSifniotis, who owns the history on the file

**Comment by jlperla** [comment]
Can you see what the OS independent way to do this in python and try to prepare a PR?

**Comment by arnavs** [comment]
Yeah. At worst think we can just do casework on whether it’s Windows or not. Will do.

**Comment by jlperla** [comment]
Try to see what the proper way is before adding in a bunch of OS specific cases

**Comment by arnavs** [comment]
Done. The command is `os.sep` after you `import os`. Will submit a PR.

**Comment by mmcky** [comment]
@arnavs this looks closed to me. I will close this.
